apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    deploy: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      namespace: default
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          #requiredDuringSchedulingIgnoredDuringExecution:
          #  nodeSelectorTerms:
          #  - matchExpressions:
          #    - key: kubernetes.io/hostname
          #      operator: In
          #      values:
          #      - node1
          #      - node2
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: environment
                operator: In
                values:
                - test
      containers:
      - name: myapp
        image: cuiyf/myapp
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
