apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: pv001
spec:
  nfs:
    server: nfs.cyf.com
    path: /data/volumes/v1
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  storageClassName: "myapp"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    name: pv002
spec:
  nfs:
    server: nfs.cyf.com
    path: /data/volumes/v2
  accessModes: ["ReadWriteOnce"]
  storageClassName: "myapp"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels:
    name: pv003
spec:
  nfs:
    server: nfs.cyf.com
    path: /data/volumes/v3
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  storageClassName: "myapp"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
  labels:
    name: pv004
spec:
  nfs:
    server: nfs.cyf.com
    path: /data/volumes/v4
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  storageClassName: "myapp"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005
  labels:
    name: pv005
spec:
  nfs:
    server: nfs.cyf.com
    path: /data/volumes/v5
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  storageClassName: "myapp"
  capacity:
    storage: 1Gi

