apiVersion: v1
kind: Service
metadata:
  name: zk-hs 
  labels:
    app: zk-hs
spec:
  ports:
  - port: 2888
    name: server
    targetPort: 2888
  - port: 3888
    name: leader-election
    targetPort: 3888
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk-cs
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
