apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: default
  labels:
    cm: eureka-cm 
data:
  eureka_service_address: http://admin:admin@eureka-0.eureka:1025/eureka,http://admin:admin@eureka-1.eureka:1025/eureka
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka-ing
  namespace: default
  labels:
    ing: eureka-ing
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~*  .*\.(gif|jpg|png|css|js|mp4)$ {
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
               proxy_set_header Host $host;
                proxy_ignore_headers Set-Cookie Cache-Control;
                proxy_hide_header Cache-Control;
                proxy_hide_header Set-Cookie;

                proxy_cache cache_one;
                proxy_cache_valid 200 302 24h;
                proxy_cache_valid 301 24h;
                proxy_cache_valid any 5m;
                expires 7d;
                add_header cache "$upstream_cache_status";

               set $mobile_rewrite do_not_perform;
               if ( $http_cookie ~* "ACCESS_TERMINAL=mobile" ) {
               }
               if ($http_user_agent  ~* "^(.*android.*)|(.*iphone.*)|(.*windows phone.*)$") {
                   set $mobile_rewrite perform;
               }
                if ($mobile_rewrite = perform) {
                        proxy_pass http://172.18.0.1:7067;
                }
                proxy_pass http://172.18.0.1:7199;
        }

spec:
  rules:
  - host: eureka.cyf.com
    http:
      paths:
      - backend:
          serviceName: eureka-svc
          servicePort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  namespace: default
  labels:
    svc: eureka-svc
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
  - name: eureka
    port: 1025
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: eureka-sts
  namespace: default
  labels:
    sts: eureka-sts
spec:
  replicas: 2
  serviceName: eureka-svc
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      namespace: default
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: registry.cn-beijing.aliyuncs.com/qianjia2018/qianjia_dev:eureka
        imagePullPolicy: Always
        ports:
        - name: eureka
          containerPort: 1025
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: eureka.client.service-url.defaultZone
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        - name: eureka.instance.hostname
          value: ${HOSTNAME}.eureka
        - name: eureka.client.register-with-eureka
          value: true
        - name: eureka.client.fetch-registry
          value: true

