apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.3
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    nodePort: 32263
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 31335
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32559
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 31410
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 30728
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: NodePort
