apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq1
  labels:
    name: rabbitmq1
spec:
  nfs:
    server: nfs.cyf.com
    path: /qj/rabbitmq/mq1
  accessModes: ["ReadWriteOnce"]
  storageClassName: "rabbitmq"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq2
  labels:
    name: rabbitmq2
spec:
  nfs:
    server: nfs.cyf.com
    path: /qj/rabbitmq/mq2
  accessModes: ["ReadWriteOnce"]
  storageClassName: "rabbitmq"
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq3
  labels:
    name: rabbitmq3
spec:
  nfs:
    server: nfs.cyf.com
    path: /qj/rabbitmq/mq3
  accessModes: ["ReadWriteOnce"]
  storageClassName: "rabbitmq"
  capacity:
    storage: 1Gi
