apiVersion: v1
kind: Service
metadata:
  name: mq-management
  labels:
    app: mq-management
spec:
  ports:
  - name: mq-management
    port: 15672
    targetPort: 15672
    nodePort: 31672
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: queue-port
    port: 5672
  - name: cluster-port
    port: 4369
  - name: dist-port
    port: 25672
  clusterIP: None
  selector:
    app: rabbitmq

