apiVersion: v1
kind: Service
metadata:
  name: es-tansport
  labels:
    app: es
spec:
  ports:
  - name: transport
    port: 9300
  clusterIP: None
  selector:
    app: es
---
apiVersion: v1
kind: Service
metadata:  
  name: es-http
  labels:  
    app: es
spec:      
  type: NodePort
  ports:   
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30010
  selector:
    app: es
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
spec:
  serviceName: es-cluster
  selector:
    matchLabels:
      app: es
  replicas: 3
  template:
    metadata:
      labels:
        app: es
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        image: elasticsearch:5.6.9
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: conf
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        readinessProbe:
          failureThreshold: 3       
          successThreshold: 1
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 10         
          timeoutSeconds: 5
        livenessProbe:              
          failureThreshold: 3       
          successThreshold: 1       
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200            
          initialDelaySeconds: 20   
          periodSeconds: 10         
          timeoutSeconds: 5
      volumes:
      - name: conf
        configMap:
          name: es-conf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "es"
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-conf
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch
    node.name: ${HOSTNAME}
    node.master: true 
    node.data: true
    network.host: "0.0.0.0"
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    discovery.zen.ping.unicast.hosts: es-tansport
    discovery.zen.minimum_master_nodes: 1
    indices.query.bool.max_clause_count: 10000       
