apiVersion: v1
kind: Service
metadata:
  name: redis
  labels: 
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 16379
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector: 
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: init-redis
        image: cuiyf/redis:5.0
        command:
        - bash
        - "-c"
        - |
          if [[ ${HOSTNAME##*-} -eq 0 ]]; then
            cp /mnt/config-map/redis-master.conf /mnt/data/redis.conf
          else
            cp /mnt/config-map/redis-slaver.conf /mnt/data/redis.conf 
          fi
        volumeMounts:
        - name: conf 
          mountPath: /mnt/data
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: redis
        image: cuiyf/redis:5.0
        command: ["/bin/sh"]
        args: ["-c", "redis-server /data/conf/redis.conf --appendonly yes"]
        ports:
        - name: redis
          containerPort: 16379
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /data/conf
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: redis-conf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "redis"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis-master.conf: |
    bind 0.0.0.0
    daemonize no
    pidfile "/var/run/redis.pid"
    port 16379                       
    timeout 300                     
    loglevel warning                        
    logfile "redis.log"                    
    databases 16
    rdbcompression yes                     
    dbfilename "redis.rdb"                     
    dir "/data"                    
    requirepass 123456
    masterauth 123456
    maxclients 10000
    maxmemory 1000mb                        
    maxmemory-policy allkeys-lru                        
    appendonly yes                       
    appendfsync always
  redis-slaver.conf: |
    bind 0.0.0.0
    daemonize no
    pidfile "/var/run/redis.pid"
    port 16379
    timeout 300
    loglevel warning
    logfile "redis.log"
    databases 16
    rdbcompression yes
    dbfilename "redis.rdb"
    dir "/data"
    requirepass 123456
    masterauth 123456
    maxclients 10000
    maxmemory 1000mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync always
    slaveof redis-0.redis 16379
